/**
 * GS-156: Validate OpenAPI specification
 * 
 * This script validates the OpenAPI/Swagger specification generated by NestJS
 * Ensures all endpoints are properly documented and meet documentation standards
 */

import { NestFactory } from '@nestjs/core';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import { AppModule } from '../src/app.module';

async function validateOpenApiSpec() {
  console.log('🔍 Validating OpenAPI specification...');

  try {
    const app = await NestFactory.create(AppModule);

    // Configure Swagger
    const config = new DocumentBuilder()
      .setTitle('Gaia Sovereign API')
      .setDescription(
        'Personal Data Vault API - Manage your sensitive information with privacy-first approach. Users control which apps access their data.',
      )
      .setVersion('1.0.0')
      .addBearerAuth(
        {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'JWT token required for authentication',
        },
        'bearer',
      )
      .addTag('Auth', 'Authentication endpoints')
      .addTag('Users', 'User profile and access management')
      .addTag('Vault', 'Secure vault operations')
      .addTag('Tokens', 'Access token management')
      .addTag('Consent', 'Data consent requests')
      .addTag('Third-Party Apps', 'Third-party application management')
      .addTag('Audit', 'Audit logs and tracking')
      .addTag('Admin', 'Administrative operations')
      .setContact(
        'Gaia Sovereign Team',
        'https://github.com/wassim205/Gaia-Sovereign',
        'support@gaiasovereign.dev',
      )
      .setLicense(
        'UNLICENSED',
        'https://github.com/wassim205/Gaia-Sovereign/blob/main/LICENSE',
      )
      .build();

    // Generate OpenAPI document
    const document = SwaggerModule.createDocument(app, config);

    // Validation checks
    const errors: string[] = [];

    // Check if document has required fields
    if (!document.openapi) {
      errors.push('Missing OpenAPI version');
    }

    if (!document.info) {
      errors.push('Missing API info section');
    }

    if (!document.paths || Object.keys(document.paths).length === 0) {
      errors.push('No API endpoints documented');
    }

    // Count documented endpoints
    const endpointCount = document.paths
      ? Object.keys(document.paths).length
      : 0;

    // Validate each endpoint
    if (document.paths) {
      for (const [path, pathItem] of Object.entries(document.paths)) {
        const methods = ['get', 'post', 'put', 'patch', 'delete', 'options'];

        for (const method of methods) {
          const operation = (pathItem as any)?.[method];

          if (operation) {
            // Check for summary
            if (!operation.summary) {
              errors.push(
                `${method.toUpperCase()} ${path}: Missing operation summary`,
              );
            }

            // Check for responses
            if (!operation.responses || Object.keys(operation.responses).length === 0) {
              errors.push(
                `${method.toUpperCase()} ${path}: Missing response documentation`,
              );
            }

            // Check for deprecated endpoints
            if (operation.deprecated) {
              console.warn(
                `⚠️  Deprecated endpoint: ${method.toUpperCase()} ${path}`,
              );
            }
          }
        }
      }
    }

    // Report results
    console.log('\n📊 OpenAPI Specification Report:');
    console.log(`   Total Endpoints: ${endpointCount}`);
    console.log(
      `   API Version: ${document.info?.version || 'Unknown'}`,
    );

    if (errors.length > 0) {
      console.error('\n❌ Validation Errors:');
      errors.forEach((error, index) => {
        console.error(`   ${index + 1}. ${error}`);
      });
      await app.close();
      process.exit(1);
    } else {
      console.log('\n✅ OpenAPI specification is valid!');
      console.log(
        `\n✨ All ${endpointCount} endpoints are properly documented`,
      );
    }

    // Generate and save specification
    const specPath = './openapi.json';
    const fs = await import('fs');
    fs.writeFileSync(specPath, JSON.stringify(document, null, 2));
    console.log(`\n💾 OpenAPI spec saved to: ${specPath}`);

    await app.close();
  } catch (error) {
    console.error('❌ Failed to validate OpenAPI specification:');
    console.error(error);
    process.exit(1);
  }
}

validateOpenApiSpec();
