FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./
COPY prisma ./prisma/

# Install dependencies
RUN npm install --ignore-engines

# Generate Prisma Client
RUN npx prisma generate

# Copy source code
COPY . .

EXPOSE 4000
CMD ["npm", "run", "start:dev"]